name: Renovate Auto-merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
  pull_request_review:
    types: [submitted]
  status: {}
  check_suite:
    types: [completed]

jobs:
  automerge:
    name: Auto-merge Renovate PRs
    runs-on: ubuntu-latest
    if: >
      github.actor == 'renovate[bot]' &&
      (github.event_name != 'pull_request_target' ||
       github.event.pull_request.user.login == 'renovate[bot]') &&
      (github.event_name != 'pull_request_review' ||
       github.event.review.state == 'approved')
    steps:
      - name: Enable auto-merge for Renovate PRs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pull } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            if (pull.mergeable_state === 'clean' || 
                pull.mergeable_state === 'unstable') {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash',
                commit_title: pull.title,
                commit_message: 'chore(deps): ' + pull.title + '\n\n' + 
                  'Automated by Renovate Bot\n' +
                  'Closes #' + context.issue.number
              });
            }
