name: Test YAML Tickets to Issues

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test YAML Tickets to Issues
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
